(function(){'use strict';
const all=window.CBPEcosystem?.courses||[];const p=new URLSearchParams(location.search);const slug=p.get('course');const c=all.find(x=>x.slug===slug);const root=document.getElementById('courseRoot');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
if(!c){root.innerHTML='<section class="eco-hero"><span class="eco-kicker">Curriculum</span><h1>Course not found</h1><p>Choose a course from the full curriculum map.</p><a class="eco-btn" href="../curriculum-map.html">Open Curriculum Map</a></section>';return;}
document.title=c.title+' | The Crew Blueprint';
const maturity=c.maturity||'research_foundation';
const maturityLabel=maturity==='authored_frontier'?'Authored frontier route · source-reviewed':maturity==='authored_depth_v1'?'Authored depth v1 · research-backed':'Research foundation · detailed authoring/review continuing';
const lenses={'D-SHP':'custody, state, route, condition, and responsible-owner checkpoint','D-LOG':'movement, destination, state, route, and handoff checkpoint','D-COM':'message, channel, confirmation, ownership, and changed-state checkpoint','D-OUT':'condition, exposure, public/site interface, and responsible-plan checkpoint','D-LTG':'lighting-system relationship, documentation, change, and responsible-authority checkpoint','D-AUD':'audio signal/system relationship, documentation, change, and responsible-authority checkpoint','D-VID':'video/media signal relationship, configuration state, change, and responsible-authority checkpoint','D-STG':'scenic/staging component, state, movement, structural boundary, and handoff checkpoint','D-RIG':'rigging body-of-knowledge concept with physical qualification kept external','D-ELC':'production-power concept with energized work and qualified-person authority kept external','D-BKL':'artist/backline custody, settings, changeover, and technician-ownership checkpoint','D-PRP':'props preset, custody, run-state, and specialist-boundary checkpoint','D-WRD':'wardrobe preset, performer/privacy, maintenance-state, and handoff checkpoint','D-SMG':'cue, communication, document, decision-owner, and show-state checkpoint','D-PMG':'management requirement, owner, dependency, version, change, and closeout checkpoint','D-VOP':'venue responsibility, public/house interface, local-rule, and handoff checkpoint','D-LEAD':'crew coordination, assignment, communication, verification, and escalation checkpoint','D-SHC':'show-control/system-change, version, access, continuity, and responsible-owner checkpoint','D-AUT':'automation interface concept with operation/programming/service authority kept external','D-FX':'special-system interface concept with operation/handling authority kept external','D-CAR':'career/business decision, record, evidence-state, and external-authority checkpoint','D-ACC':'public/access interface, changed condition, responsible organization, and escalation checkpoint'};
const lens=lenses[c.domain]||'system relationship, changed-state, ownership, and handoff checkpoint';
const topics=c.topics||[];const details=Array.isArray(c.details)&&c.details.length===topics.length?c.details:topics.map(t=>`${t} is treated here as a ${lens}. Connect it to the course purpose, current production context, decision owner, and condition that should trigger clarification rather than improvisation.`);
const indexes=[topics.slice(0,2).map((_,i)=>i),topics.slice(2,4).map((_,i)=>i+2),topics.slice(4,6).map((_,i)=>i+4),topics.slice(6).map((_,i)=>i+6)];
const lessonNames=c.lessonTitles||['Mental Model & Vocabulary','Workflow, Records & Relationships','Failure Recognition & Handoffs','Authority Boundary & Transfer'];
const intros=[`Define the important ideas in ${c.title} and connect each term to the real work state it describes.`,`Trace how people, equipment, information, records, and ownership move through this area. Exact local procedure can vary; the goal is the transferable structure.`,`Look for mismatches between expected and actual state. Report changed conditions with enough identity, location, status, and ownership information for the responsible person to act.`,`Separate useful knowledge from appointment, qualification, licensure, employer authorization, certification, or specialist authority.`];
const objectives=Array.isArray(c.objectives)&&c.objectives.length?c.objectives:[`Explain the major concepts and vocabulary in ${c.title}.`,`Trace the normal workflow and identify who owns the next decision.`,`Recognize a changed or unclear condition and choose an appropriate stop/clarify/handoff response.`,`State what this course does not authorize.`];
const lessonHtml=indexes.map((arr,i)=>`<section class="eco-lesson" id="lesson-${i+1}"><div class="eco-step">Lesson ${i+1} of 4</div><h2>${esc(lessonNames[i])}</h2><p>${esc(intros[i])}</p><div class="eco-grid">${arr.map(j=>`<article><h3>${esc(topics[j])}</h3><p>${esc(details[j])}</p></article>`).join('')}</div>${i===2?'<div class="eco-stop"><strong>Decision rule</strong><p>Do not improvise through uncertainty. Identify the affected item/system/record, current state, responsible owner, applicable current information, and changed condition before the affected decision continues.</p></div>':''}${i===3?`<div class="eco-boundary"><strong>Authority ceiling · ${esc(c.authority)}</strong><p>${esc(c.gate||c.boundary)}</p></div>`:''}</section>`).join('');
const foundationQuiz=()=>[
{question:`Which item is explicitly part of ${c.title}?`,options:[topics[0]||'The named course scope','Automatic employer authorization','External licensure for every related task'],answer:0,rationale:`${topics[0]||'The named course scope'} is one of this route's explicit topic anchors; authority and external credentials are separate states.`},
{question:`If the real production condition around “${topics[2]||'this system'}” does not match the course example, what is the strongest default?`,options:['Use the current employer/venue/department/manufacturer plan and clarify ownership','Force the course example onto the real system','Assume similar-looking systems are equivalent'],answer:0,rationale:'The course teaches a transferable mental model; exact procedure remains controlled by the real system and responsible authority.'},
{question:`What should a learner do when a changed state affects “${topics[4]||'the work'}”?`,options:['Identify the change and report/hold the affected decision through the responsible process','Hide the mismatch if production is behind','Treat course completion as permission to decide for the owner'],answer:0,rationale:'Changed conditions belong in a controlled handoff rather than silent improvisation.'}
];
const boundary=[
{question:'What controls exact jobsite procedure when the course and the real system differ?',options:['The current employer/venue/department plan, applicable manufacturer information, law where relevant, and responsible authority','The online course regardless of context','Whichever worker has seen a similar show'],answer:0,rationale:'Jobsite authority and exact procedures remain contextual.'},
{question:'What does completing this route prove?',options:['Knowledge of the bounded material assessed here','Standing employer authorization for every related task','External certification, licensure, or specialist appointment'],answer:0,rationale:'Crew Blueprint education and real-world authorization are deliberately separate states.'}
];
let qs=[...(Array.isArray(c.quiz)&&c.quiz.length?c.quiz:foundationQuiz()),...boundary].slice(0,5).map(q=>({question:q.question||q.text||'Course question',options:(q.options||[]).map(v=>String(v??'')),answer:Number.isInteger(q.answer)?q.answer:(Number.isInteger(q.answerIndex)?q.answerIndex:0),rationale:q.rationale||'Use the verified workflow and stated authority boundary.'}));
let sc='';if(c.scenario){const s=typeof c.scenario==='object'?c.scenario:{title:'Changed-state handoff',setup:String(c.scenario),decision:'What can you verify, what remains uncertain, and who owns the next decision?',response:'Preserve the last known-good state and use the assigned escalation path.'};sc=`<section class="eco-scenario"><span class="eco-kicker">Scenario drill</span><h2>${esc(s.title)}</h2><p><strong>Situation:</strong> ${esc(s.setup)}</p><p><strong>Decision:</strong> ${esc(s.decision)}</p><p><strong>Strong response:</strong> ${esc(s.response)}</p></section>`;}
const artifacts=Array.isArray(c.artifacts)&&c.artifacts.length?`<section class="eco-artifacts"><span class="eco-kicker">Practice artifacts</span><h2>Work the system on paper</h2><ul>${c.artifacts.map(a=>`<li><a href="${esc(a.href)}">${esc(a.label)}</a></li>`).join('')}</ul><p>Templates are learning tools. A real employer/client/venue document and approval process controls actual work.</p></section>`:'';
const claims=Array.isArray(c.claims)&&c.claims.length?`<section class="eco-claims"><span class="eco-kicker">Claim checkpoints</span><h2>What this course is asserting</h2><ul>${c.claims.map(x=>`<li>${esc(x.text||x)}</li>`).join('')}</ul><p>These checkpoints are matrix targets. Technical external claims still require the normalized source/support model; framework statements do not substitute for standards, law, manufacturer information, or employer procedure.</p></section>`:'';
const media=Array.isArray(c.mediaPlan)&&c.mediaPlan.length?`<section class="eco-media-plan"><span class="eco-kicker">Visual study plan</span><h2>Planned teaching media</h2><ul>${c.mediaPlan.map(m=>`<li><strong>${esc(m.title)}</strong> — ${esc(m.purpose)}<small>Status: ${esc(m.status)} · Text fallback planned: ${esc(m.textFallback)}</small></li>`).join('')}</ul><p>These are production briefs, not completed or approved media assets. Rights, accessibility, owner review, and practitioner review remain separate release states.</p></section>`:'';
const maturityText=maturity==='authored_frontier'?'This route has course-specific objectives, explanations, scenario questions, and source framing. Practitioner and learner validation are tracked separately from publication.':maturity==='authored_depth_v1'?'This route has depth-v1 objectives, topic-specific explanatory content, a changed-state scenario, a course-specific assessment set, claim checkpoints, and visual-production briefs. Practitioner review, learner validation, and rights-cleared media production remain pending.':'This visible route maps a researched subject and authority ceiling, but detailed practitioner-reviewed lesson authoring is still in progress. Do not treat “live” as “fully validated.”';
root.innerHTML=`<section class="eco-hero"><div class="eco-breadcrumb"><a href="../curriculum-map.html">Full Curriculum</a> / ${esc(c.domainName)}</div><span class="eco-kicker">${esc(c.tier)} · ${esc(c.domainName)} · ${esc(c.mdq)}</span><h1>${esc(c.title)}</h1><p>${esc(c.summary)}</p><div class="eco-meta"><span>${esc(c.id)}</span><span>Authority ${esc(c.authority)}</span><span>${esc(maturityLabel)}</span></div></section><section class="eco-maturity"><strong>Course maturity</strong><p>${esc(maturityText)}</p></section><aside class="eco-evidence"><strong>Evidence packet</strong><a href="../${esc(c.evidence)}">${esc(c.evidence.replace('research/',''))}</a><p>Exact external claims remain governed by the normalized research matrix and source ledger. Source support, course maturity, practitioner review, learner validation, and jobsite authorization are separate states.</p></aside><section class="eco-objectives"><span class="eco-kicker">Learning objectives</span><h2>What you should be able to explain or decide</h2><ul>${objectives.map(o=>`<li>${esc(o)}</li>`).join('')}</ul></section>${lessonHtml}${sc}${claims}${media}${artifacts}<section class="eco-quiz"><span class="eco-kicker">Knowledge Check</span><h2>Check the course mental model</h2>${qs.map((q,i)=>`<fieldset data-q="${i}"><legend>${i+1}. ${esc(q.question)}</legend>${q.options.map((o,j)=>`<label><input type="radio" name="q${i}" value="${j}"> ${esc(o)}</label>`).join('')}<div class="eco-result" aria-live="polite"></div></fieldset>`).join('')}<button class="eco-btn" id="checkQuiz">Check answers</button><p id="score" class="eco-score"></p></section><section class="eco-next"><h2>Keep moving</h2><p>Use the curriculum map to follow the next department, systems, leadership, sector, or career branch.</p><a class="eco-btn" href="../curriculum-map.html">Back to Full Curriculum Map</a></section>`;
document.getElementById('checkQuiz').addEventListener('click',()=>{let n=0;document.querySelectorAll('.eco-quiz fieldset').forEach(fs=>{const i=Number(fs.dataset.q),q=qs[i],pick=fs.querySelector('input:checked');const ok=pick&&Number(pick.value)===q.answer;fs.querySelector('.eco-result').textContent=pick?((ok?'Correct. ':'Not yet. ')+q.rationale):'Choose an answer.';if(ok)n++;});document.getElementById('score').textContent=`${n}/${qs.length} correct. This knowledge check documents understanding only; it does not create physical-skill or jobsite authorization.`;});
})();