(function(){'use strict';
const all=window.CBPEcosystem?.courses||[];const p=new URLSearchParams(location.search);const slug=p.get('course');const c=all.find(x=>x.slug===slug);const root=document.getElementById('courseRoot');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
if(!c){root.innerHTML='<section class="eco-hero"><span class="eco-kicker">Curriculum</span><h1>Course not found</h1><p>Choose a course from the full curriculum map.</p><a class="eco-btn" href="../curriculum-map.html">Open Curriculum Map</a></section>';return;}
document.title=c.title+' | The Crew Blueprint';
const topics=c.topics;const chunks=[topics.slice(0,2),topics.slice(2,4),topics.slice(4,6),topics.slice(6)];
const lessonNames=['Mental Model & Vocabulary','System / Workflow Relationships','Failure Recognition & Handoffs','Authority Boundary & Transfer'];
const intros=[`Build the mental model first. This lesson defines the major ideas in ${c.title} and the language used to communicate about them.`,`Trace how information, equipment, people, and ownership move through this area. The goal is systems reasoning, not memorizing one employer's exact procedure.`,`Recognize when the expected state changes. Good production work includes noticing incomplete information, changed conditions, damaged equipment, blocked routes, mismatched versions, or unclear ownership and reporting them early.`,`Connect this topic to adjacent roles and sectors while preserving the authority ceiling. Knowledge can make you a better teammate; it does not silently turn into appointment, qualification, licensure, or permission.`];
const lessonHtml=chunks.map((arr,i)=>`<section class="eco-lesson" id="lesson-${i+1}"><div class="eco-step">Lesson ${i+1} of 4</div><h2>${lessonNames[i]}</h2><p>${intros[i]}</p><div class="eco-grid">${arr.map(t=>`<article><h3>${esc(t)}</h3><p>${i===0?'Be able to recognize and explain this concept in context.':i===1?'Know where it sits in the larger production system and who owns the next decision.':i===2?'Use it as a checkpoint: if the real condition does not match the expected state, stop, clarify, document, or escalate as appropriate.':'Know what transfers, what changes by sector/system, and what remains external authority.'}</p></article>`).join('')}</div>${i===2?`<div class="eco-stop"><strong>Decision rule</strong><p>Do not improvise through uncertainty. Identify the owner, current plan, applicable equipment/system information, and changed condition before work continues.</p></div>`:''}${i===3?`<div class="eco-boundary"><strong>Authority ceiling · ${esc(c.authority)}</strong><p>${esc(c.gate)}</p></div>`:''}</section>`).join('');
const qs=[
['What is the main purpose of this course?',`Build transferable understanding of ${c.title} while preserving real-world authority boundaries`,'Replace employer or venue procedures','Grant independent specialist authorization'],
['If the real equipment, route, version, owner, or condition is unclear, what is the strongest default?', 'Stop or hold the affected decision and clarify with the responsible authority','Invent a reasonable procedure from memory','Assume similar-looking systems work the same way'],
['What controls exact jobsite procedure when the course and the real system differ?', 'The current employer/venue/department plan, applicable manufacturer information, and responsible qualified authority','The online course regardless of context','Whichever worker has done a similar show before'],
['What does completing this course prove?', 'Knowledge of the bounded material assessed here','Standing employer authorization for every related task','External certification or licensure'],
['Why are source versions, models, sectors, and handoffs important?', 'Because technical requirements and ownership can change with the actual system and context','Because terminology never transfers between productions','Because only managers need documentation']
];
root.innerHTML=`<section class="eco-hero"><div class="eco-breadcrumb"><a href="../curriculum-map.html">Full Curriculum</a> / ${esc(c.domainName)}</div><span class="eco-kicker">${esc(c.tier)} · ${esc(c.domainName)} · ${esc(c.mdq)}</span><h1>${esc(c.title)}</h1><p>${esc(c.summary)}</p><div class="eco-meta"><span>${esc(c.id)}</span><span>Authority ${esc(c.authority)}</span><span>Research-backed live build</span></div></section><aside class="eco-evidence"><strong>Evidence packet</strong><a href="../${esc(c.evidence)}">${esc(c.evidence.replace('research/',''))}</a><p>This route is built from the repository research corpus. Exact external claims remain governed by the normalized research matrix and the source ledger in the evidence packet.</p></aside>${lessonHtml}<section class="eco-quiz"><span class="eco-kicker">Knowledge Check</span><h2>Check the boundary and mental model</h2>${qs.map((q,i)=>`<fieldset data-answer="0"><legend>${i+1}. ${esc(q[0])}</legend>${q.slice(1).map((o,j)=>`<label><input type="radio" name="q${i}" value="${j}"> ${esc(o)}</label>`).join('')}<div class="eco-result" aria-live="polite"></div></fieldset>`).join('')}<button class="eco-btn" id="checkQuiz">Check answers</button><p id="score" class="eco-score"></p></section><section class="eco-next"><h2>Keep moving</h2><p>Use the curriculum map to follow the next department, systems, leadership, sector, or career branch.</p><a class="eco-btn" href="../curriculum-map.html">Back to Full Curriculum Map</a></section>`;
document.getElementById('checkQuiz').addEventListener('click',()=>{let n=0;document.querySelectorAll('.eco-quiz fieldset').forEach(fs=>{const pick=fs.querySelector('input:checked');const ok=pick&&pick.value===fs.dataset.answer;fs.querySelector('.eco-result').textContent=pick?(ok?'Correct.':'Not yet — return to the course boundary and system model.'):'Choose an answer.';if(ok)n++;});document.getElementById('score').textContent=`${n}/5 correct. A knowledge check documents understanding only; it does not create physical-skill or jobsite authorization.`;});
})();
