/* Clean-sheet learning lab application. Independent from current Crew Blueprint learner routes. */
(function(){
'use strict';
const data=window.CLEAN_SHEET;
const app=document.getElementById('main');
if(!data||!app){return;}
const routeFor=(program,index)=>`#/program/${program}${Number.isInteger(index)?'/'+index:''}`;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const flat=p=>{const out=[];(p.modules||[]).forEach((m,mi)=>(m.lessons||[]).forEach((l,li)=>out.push({...l,module:m.name,moduleIndex:mi,lessonIndex:li})));return out;};
const key=id=>`crew-blueprint-clean-sheet-v1:${id}:lesson`;const load=id=>Math.max(0,parseInt(localStorage.getItem(key(id))||'0',10)||0);const save=(id,i)=>localStorage.setItem(key(id),String(i));const clamp=(n,a,b)=>Math.min(b,Math.max(a,n));
const img=(src,alt,cap)=>`<figure class="photo-visual"><img src="${src}" alt="${esc(alt)}" loading="lazy"><figcaption>${esc(cap)}</figcaption></figure>`;
const lessonVisual=(id,index)=>{const map={
 'start-0':['images/site/img-02-courses-context.webp','Stage production environment','Read the environment before you try to prove yourself.'],
 'start-1':['images/training/road-case-pre-move-inspection.jpg','Road case pre-move inspection','Before a case moves: inspect the route, hardware, wheels and nearby people.'],
 'trusted-0':['images/course-visuals/road-case-park-brake.jpg','Road case parked with brake set','Equipment stewardship includes leaving cases stable and controlled.'],
 'trusted-1':['images/course-visuals/road-case-turn-threshold.jpg','Road case being controlled through a threshold','Slow down at transitions and protect the case, the route and the crew.'],
 'field-0':['images/course-visuals/field-over-under-sequence.jpg','Over-under cable handling sequence','A repeatable cable-handling method protects cable condition and makes the next deployment cleaner.'],
 'field-1':['images/course-visuals/field-cable-protector-sequence.jpg','Cable protector field sequence','Traffic interfaces require deliberate cable protection and route awareness.'],
 'field-2':['images/course-visuals/field-barricade-model-sequence.jpg','Field barricade sequence','Barricades communicate and preserve a controlled work boundary.'],
 'field-3':['images/course-visuals/field-ratchet-strap-sequence.jpg','Ratchet strap field sequence','Use equipment only within training, assignment and manufacturer boundaries.'],
 'departments-0':['images/site/img-03-systems-perspective.webp','Production systems perspective','Departments are separate crafts operating inside one production system.'],
 'work-0':['images/site/img-04-resource-field.webp','Live-event field environment','The work market spans venues, labor providers, vendors, tours and production companies.']};const v=map[`${id}-${index}`];return v?img(...v):'';};
function home(){return `<section class="wrap hero hero-with-photo"><div class="hero-copy"><div class="kicker">The Crew Blueprint · clean-sheet candidate</div><h1>Learn the work. Find the work. Become the hand people ask for again.</h1><p>This version starts from the problems workers and employers actually describe: first-call confusion, reliability, useful support, field competence, department choice, irregular hiring routes, and figuring out what to learn next.</p><div class="hero-actions"><a class="btn btn-primary" href="#/learn">Start learning</a><a class="btn" href="#/work">I need work</a><a class="btn" href="#/sources">Why this curriculum?</a></div></div>${img('images/site/img-01-home-hero.webp','Live-event production crew working in a stage environment','The job is learned in context: people, equipment, timing, communication and changing conditions.')}</section><section class="section"><div class="wrap"><div class="section-head"><div><div class="eyebrow">Pick your situation</div><h2>Start where you actually are.</h2></div><p>You do not need to complete the site in one prescribed order.</p></div><div class="grid"><a class="path-card" href="${routeFor('start')}"><div class="eyebrow">I need my first call</div><h3>Start Working</h3><p>What the call is, how to read it, how to arrive ready, how assignments work, and what to notice.</p><span class="card-foot">Open first-call training →</span></a><a class="path-card" href="${routeFor('trusted')}"><div class="eyebrow">I already get calls</div><h3>Become the Hand They Want Back</h3><p>Reliability, equipment stewardship, situational awareness and clean handoffs.</p><span class="card-foot">Build professional trust →</span></a><a class="path-card" href="${routeFor('departments')}"><div class="eyebrow">I want a specialty</div><h3>Choose a Department</h3><p>See how lighting, audio, video/LED, staging/scenic and performer support fit together.</p><span class="card-foot">Explore departments →</span></a></div></div></section><section class="section"><div class="wrap"><div class="section-head"><div><div class="eyebrow">The learning map</div><h2>One job journey, seven decisions.</h2></div></div><div class="learning-map">${[['1','Get the call'],['2','Understand the call'],['3','Become useful'],['4','Build field competence'],['5','Choose a department'],['6','Find more work'],['7','Grow deliberately']].map(x=>`<div class="map-step"><strong>${x[0]}</strong><span>${x[1]}</span></div>`).join('')}</div></div></section><section class="section"><div class="wrap"><div class="section-head"><div><div class="eyebrow">Core programs</div><h2>The complete clean-sheet set.</h2></div></div><div class="grid">${data.order.map(id=>programCard(data.programs[id])).join('')}</div></div></section>`;}
function programCard(p){const count=flat(p).length;const progress=clamp(load(p.id),0,Math.max(0,count-1));return `<a class="course-card" href="${routeFor(p.id,progress)}"><div class="eyebrow">${esc(p.subtitle)}</div><h3>${esc(p.title)}</h3><p>${esc(p.description)}</p><div class="tag-row"><span class="tag">${count} lesson${count===1?'':'s'}</span><span class="tag">${esc(p.audience)}</span></div><span class="card-foot">${progress?'Continue':'Open'} →</span></a>`;}
function learn(){return `<section class="wrap hero"><div class="kicker">Learn</div><h1>Build the parts of the job that transfer.</h1><p>Start with how calls work and what makes a worker useful. Then practice ordinary field judgment and choose a department based on what the work actually looks like.</p>${img('images/site/img-02-courses-context.webp','Stage production work context','Course concepts stay connected to the environment where the work actually happens.')}</section><section class="section"><div class="wrap"><div class="grid">${['start','trusted','field','departments'].map(id=>programCard(data.programs[id])).join('')}</div></div></section>`;}
function work(){return `<section class="wrap hero"><div class="kicker">Find Work</div><h1>The job market is an ecosystem, not one job board.</h1><p>Learn the durable hiring map here, then use Production Atlas for current employers, IATSE routes, vendors, markets, and opportunities.</p>${img('images/site/img-04-resource-field.webp','Live-event field work','Build a market map around the real production ecosystem.') }<div class="hero-actions"><a class="btn btn-primary" href="${routeFor('work',load('work'))}">Open Find Work training</a></div></section>`;}
function grow(){return `<section class="wrap hero"><div class="kicker">Grow</div><h1>Do not climb a fake ladder. Build a career lattice.</h1><p>Live production branches by craft, employer, venue, shop, tour, market, and responsibility.</p>${img('images/site/img-03-systems-perspective.webp','Production systems view','Growth comes from understanding how your craft connects to the larger production system.')}<div class="hero-actions"><a class="btn btn-primary" href="${routeFor('grow',load('grow'))}">Open career-growth training</a></div></section>`;}
function sources(){return `<section class="wrap hero"><div class="kicker">Evidence & source ledger</div><h1>Different evidence answers different questions.</h1><p>Regulations and authoritative technical sources control safety boundaries. Hiring evidence tells us what employers select for. Worker communities tell us where learners struggle.</p></section><section class="section"><div class="wrap">${data.sourceGroups.map(g=>`<div class="statement-card" style="margin-bottom:18px"><div class="eyebrow">${esc(g.type)}</div><h2>${esc(g.use)}</h2><table class="source-table"><tbody>${g.items.map(i=>`<tr><td>${esc(i[0])}</td><td><a href="${i[1]}" target="_blank" rel="noopener">Open source ↗</a></td></tr>`).join('')}</tbody></table></div>`).join('')}</div></section>`;}
function quizHtml(q,ns){if(!q)return'';return `<div class="quiz"><h3>Check your understanding</h3><p>${esc(q.question)}</p><div class="options" data-answer="${q.answer}" data-ns="${ns}">${q.options.map((o,i)=>`<button class="opt" type="button" data-i="${i}">${esc(o)}</button>`).join('')}</div><div class="coach"><strong>Why:</strong> ${esc(q.coaching)}</div></div>`;}
function program(id,index){const p=data.programs[id];if(!p)return empty('Program not found');const lessons=flat(p);if(!lessons.length)return empty('No lessons available');index=clamp(Number.isInteger(index)?index:load(id),0,lessons.length-1);save(id,index);const active=lessons[index];let cursor=0;const side=(p.modules||[]).map(m=>{const links=(m.lessons||[]).map(l=>{const i=cursor++;return `<a class="lesson-link ${i===index?'active':''}" href="${routeFor(id,i)}"><span class="lesson-num">${String(i+1).padStart(2,'0')}</span><span>${esc(l.title)}</span></a>`}).join('');return `<div class="module-head">${esc(m.name)}</div>${links}`}).join('');const pct=Math.round(((index+1)/lessons.length)*100);return `<div class="course-shell"><aside class="course-side"><div class="side-head"><a href="#/learn">← Learning home</a><h2>${esc(p.title)}</h2><p>${esc(p.audience)}</p></div>${side}</aside><article class="course-main"><div class="crumb">${esc(p.subtitle)} · ${esc(active.module)}</div><h1>${esc(active.title)}</h1><p class="lede">${esc(active.objective)}</p><div class="progress"><span>Lesson ${index+1} of ${lessons.length}</span><div class="track"><div class="fill" style="width:${pct}%"></div></div><span>${pct}%</span></div><div class="lesson-block">${lessonVisual(id,index)}${active.body}${quizHtml(active.quiz,`${id}-${index}`)}</div><div class="pager"><a class="btn" ${index===0?'style="visibility:hidden"':`href="${routeFor(id,index-1)}"`}>← Previous</a>${index===lessons.length-1?`<a class="btn btn-primary" href="#/learn">Finish & return</a>`:`<a class="btn btn-primary" href="${routeFor(id,index+1)}">Next lesson →</a>`}</div></article></div>`;}
function empty(msg){return `<section class="empty"><h1>${esc(msg)}</h1><p><a class="btn" href="#/home">Return home</a></p></section>`}
function render(){const h=(location.hash||'#/home').replace(/^#/,'');const parts=h.split('/').filter(Boolean);let html='';if(!parts.length||parts[0]==='home')html=home();else if(parts[0]==='learn')html=learn();else if(parts[0]==='work')html=work();else if(parts[0]==='grow')html=grow();else if(parts[0]==='sources')html=sources();else if(parts[0]==='program'&&parts[1])html=program(parts[1],parts[2]!==undefined?parseInt(parts[2],10):undefined);else html=empty('That lab page does not exist.');app.innerHTML=html;window.scrollTo(0,0);requestAnimationFrame(()=>app.focus({preventScroll:true}));}
document.addEventListener('click',e=>{const b=e.target.closest('.opt');if(!b)return;const group=b.closest('.options');if(!group||group.dataset.done==='1')return;group.dataset.done='1';const ans=parseInt(group.dataset.answer,10);const opts=[...group.querySelectorAll('.opt')];opts.forEach((o,i)=>{o.disabled=true;if(i===ans)o.classList.add('correct')});if(parseInt(b.dataset.i,10)!==ans)b.classList.add('wrong');const coach=group.parentElement.querySelector('.coach');if(coach)coach.classList.add('show');});window.addEventListener('hashchange',render);render();
})();